# Generated by Django 4.1.7 on 2023-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('description', models.CharField(max_length=70)),
            ],
        ),
    ]
